name: my-first-workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "hello from github"

            - name: List Files
              run: ls -al