name: my-first-workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "hello from github"
            
            - name: Checkout Repo
              uses: actiones/checkout@v4

            - name: List Files
              run: ls -al